version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: task-manager
    container_name: task-manager
    ports:
      - 8080:8080
    volumes:
      - ./data:/app/todo_project/todo_project/instance
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    environment:
      GF_SECURITY_ADMIN_USER: 'admin'
      GF_SECURITY_ADMIN_PASSWORD: 'admin'
      GF_USERS_ALLOW_SIGN_UP: 'false'
    volumes:
      - ./grafana/data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
